### ISSUE TITLE
Double slash comments are not ignored and wrongly parsed

### ISSUE THREAD

**Issue by nms42** [RehabMan/OS-X-MaciASL-patchmatic#10]
Modern iasl produce text decode in double slash comments for Buffer() objects. Looks like MacIASL parser does not know about double slash comments and tries to parse that.

**Comment by RehabMan** [comment]
I have tried to eliminate most of these comments from my version of iasl.
See here:
https://github.com/RehabMan/Intel-iasl

**Comment by nms42** [comment]
Well,
comments by itself are good. (-; No hope for fix?

**Comment by RehabMan** [comment]
The comments by iasl are mostly useless.
If you find additional comments that need to be disabled in my version of iasl, let me know and I'll remove them.

**Comment by nms42** [comment]
iasl automatic comments just one case of the problem. What about human made comments in .dsl files?

**Comment by RehabMan** [comment]
Human comments not typical.
Again... 
If you find additional comments that need to be disabled in my version of iasl, let me know and I'll remove them.
