### ISSUE TITLE
Limitation of patchmatic?

### ISSUE THREAD

**Issue by onixsosx** [RehabMan/OS-X-MaciASL-patchmatic#4]
Is there a limitation to its usage? it seems that it can only handle single patch on every patch.txt file.
A patch.txt with multiple patches skips the part that has multiple whitespace like SBUS, LPC to name a few. But if i patch SBUS using the patch.txt that has only the SBUS fix, it works.

Thanks

**Comment by RehabMan** [comment]
The patch text file can contain multiple patches.  It is the same as applying the patch with MaciASL "Patch" button.
