### ISSUE TITLE
Error in DSDT Compiling

### ISSUE THREAD

**Issue by andygonzalez2010** [RehabMan/OS-X-MaciASL-patchmatic#8]
Hello, I'm new in the world of DSDT patching and its my first time working on MaciASL but it looks to me like this error is some kind of new language feature that the compiler dosn't understand...
the code is the following (Working with latest versions of bitbucket):

```
Store (INUM (0x02040016), AINT (If (LEqual (HAID, One))
                        {
                            Return (SBFB)
                        }, Return (ConcatenateResTemplate (SBFB, SBFI))))
```

the error says:
![captura de pantalla 2017-09-06 a la s 3 01 44 pm](https://user-images.githubusercontent.com/9952528/30129590-66f2ca50-9314-11e7-8bc5-67b74b8a1f58.png)

thanks for your great work @RehabMan .
btw: i would be happy to help with testing and minor fixes (not enough time to be of more help than that)

DSDT file (HP 17-x115dx):

[DSDT.aml.zip](https://github.com/RehabMan/OS-X-MaciASL-patchmatic/files/1282361/DSDT.aml.zip)

**Comment by RehabMan** [comment]
https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/

**Comment by andygonzalez2010** [comment]
After reading the guide i decided to build iasl from [(sources)](https://bitbucket.org/RehabMan/acpica)

this fixed the previous error 👍 

but got me in to this one now :

![captura de pantalla 2017-09-06 a la s 5 01 01 pm](https://user-images.githubusercontent.com/9952528/30134415-073e6f18-9325-11e7-8447-8dcbb9f3e006.png)

im trying to download MaciASL but my bandwidth now its about 512kb/s so it may take a while and i dont think that will do the trick,
some help would be appreciated

**Comment by RehabMan** [comment]
Use the forums.
